name: chezmoi
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - 'v*'
jobs:
  test:
    strategy:
      matrix:
        go-version:
        - 1.14.x
        os:
        - macos-latest
        - ubuntu-latest
        #- windows-latest # FIXME
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate
      if: matrix.os == 'ubuntu-latest'
      run: |
        go generate
        git diff --exit-code
    - name: Build
      run: go build ./...
    - name: Run
      run: go run . --version
    - name: Test
      run: go test -race ./...
    - name: Lint
      if: matrix.os == 'ubuntu-latest'
      run: make lint
    - name: Check formatting
      if: matrix.os == 'ubuntu-latest'
      run: |
        make format
        git diff --exit-code
    - name: Install snapcraft
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
    - name: Release
      if: matrix.os == 'ubuntu-latest'
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --skip-publish --snapshot
    - name: Test release
      if: matrix.os == 'ubuntu-latest'
      run: |
        # verify that version information is embedded correctly
        ./dist/chezmoi-cgo_linux_amd64/chezmoi --version | tee /dev/stderr | grep -q "chezmoi version v"
        ./dist/chezmoi-cgo_linux_amd64/chezmoi --version | tee /dev/stderr | grep -q "chezmoi version v"
        ./dist/chezmoi-nocgo_linux_386/chezmoi --version | tee /dev/stderr | grep -q "chezmoi version v"
        ./dist/chezmoi-nocgo-snap_linux_386/chezmoi --version | tee /dev/stderr | grep -q "chezmoi version v"
  release:
    name: Release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
    - test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Cache Go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install snapcraft
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -yq --no-install-suggests --no-install-recommends install snapcraft
    - name: Snapcraft Login
      if: success() && startsWith(github.ref, 'refs/tags/v')
      env:
        SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
      run: |
        snapcraft login --with <(echo "$SNAPCRAFT_LOGIN")
    - name: Release
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
